### ISSUE TITLE
Collaborate on Jupyterhub Notebook PVC Resizing

### ISSUE THREAD

**Issue by anishasthana** [operate-first/blueprint#51]
A common failure scenario for JupyterHub users is notebook server PVCs running out of storage capacity. Ideally we can update the ODH operator to proactively increase PVC sizes when it sees that a user is close to running out of space. Since @HumairAK and @4n4nd did a POC on this some time ago it'd be great if we could leverage your experience!

**Comment by 4n4nd** [comment]
There is a community operator available (`Volume Expander Operator`) that we could use for automatic PVC resizing instead of modifying the odh operator.
Some documentation for it is available here: [link](https://www.openshift.com/blog/automating-volume-expansion-management-an-operator-based-approach)
