### ISSUE TITLE
Secrets and passwords keyring and exchange point

### ISSUE THREAD

**Issue by tumido** [operate-first/blueprint#92]
Related to: https://github.com/operate-first/blueprint/issues/81 or secrets in https://github.com/open-infrastructure-labs/zero-openshift-install

We need a place where we can store and exchange access to secrets like GPG keys, SSH keys, IPMI credentials, AWS credentials and so on. Not every secret can be fitted into a sops resource.

Options:
- GPG encrypted files in a repo
- [gopass](https://github.com/gopasspw/gopass) as some of us are used to from AICoE
- RedHat Bitwarden (RH only, not very community-friendly and transparent)

Any ideas?

/cc @goern @rbo @HumairAK @larsks

**Comment by rbo** [comment]
Here a bunch of credentials and secrets I have stored on my workstation related to the Hetzner Setup:
 * Hetzner Account credentials (To order and maintain the server)
 * SSH private key for hetzner machines
 * Hetzner Robot API Key
 * Hetzner Cloud API Key
 * GCP Service Account secret file
 * Red Hat Pull Secret for cluster setup

**Comment by larsks** [comment]
I think we've already established that there are real problems with "store encrypted files in a git repository", because it becomes effectively impossible to recover from a key compromise: even if you rewrite the history of the "main" repository, you don't know how many copies of the old repository are out there that would be vulnerable to someone with copies of the old keys.

You're going to see the same issue with just about any form of distributed storage, because as long as someone has access to the history of the password store, old keys continue to be valid.

For actual security, you need a single point of storage (perhaps with some sort of secure backup), so that in the event of a key compromise it's possible to invalidate all access from prior keys. I'm not aware of any open source solutions that offer this level of security while still permitting group collaboration. Most open source solutions really seem to be focused on the individual user.

I think we're going to need some sort of "hosted" solution, whether that means "hosted by us" or "provided by a third party".

**Comment by tumido** [comment]
Let's talk to AppSRE, OpenCloudLabs (who else?) to see how they do this and what we can learn from them.

**Comment by rbo** [comment]
Customer asking me often about HasiCorp Vault integration. Next week on the OpenShift Usergroup we have a talk about OpenShift & HashiCorp. I will share more details after the event.

**Comment by tumido** [comment]
Can we attend the event @rbo?

**Comment by rbo** [comment]
Of course, unfortunately, the hashicorp session is in German
https://www.openshift-anwender.de/2021/06/09/jetzt-anmelden-zum-15-openshift-anwendertreffen/

**Comment by tumido** [comment]
Time to learn german then. :smile:  Unfortunately I'm not such a quick learner :smile:

**Comment by tumido** [comment]
Let's decide on trying this out then. I'll create a separate spike issue to try this out and schedule it for next/following sprint.

**Comment by rbo** [comment]
The intention was not only for the GitOps approach. More or less for us, to store SSH-keys, cloud-api keys .. somewhere...

**Comment by tumido** [comment]
So, let's explore:

- [ ] Bitwarden for secrets exchange between OPS team/users  https://github.com/operate-first/SRE/issues/363
- [ ] If the secret can be automated via asymmetric crypto, let's store public keys in git and provide access that way (SSH/GPG etc.)
- [ ] If secrets are required in automation and can't be stored in git (without ksops), let's try Vault.  https://github.com/operate-first/support/issues/298

Let's try this and if it works, let's ADR it.
